### ISSUE TITLE
Artnet not working when outputting artnet from QuickQ. Fixture works OK with sACN

### ISSUE THREAD

**Issue by lxdesigner** [Chauvet-Pro/MAVERICKFORCESPROFILE#1]
- Ping all and good
- Firmware version: V1.21005
- QuickQ V9.3 

Reported on https://secure.helpscout.net/conversation/2415796074/328703?folderId=156516

**Comment by lxdesigner** [comment]
Team this is Phil Watson please get in touch with me if you need more access to above.

**Comment by dgooch5200** [comment]
@lxdesigner  What QuickQ are you using, and can you send your show file?

**Comment by lxdesigner** [comment]
Hi David:

QuickQ 20. 

We were testing outside of the patch. Let’s chat further and I can show you around on Helpscout where I can set you up to view notes from my troubleshooting with the customer during our phone call. 

I’m trying to avoid having to copy and paste or create an email and copy and paste to that.

**Comment by dgooch5200** [comment]
Not a fixture problem.
